site_name: Openbox Dotfiles
site_description: A highly customized, lightweight, and plug-and-play Openbox configuration.
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: light blue
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy

nav:
  - Home: index.md
  - Installation: installation.md
  - Theming: theming.md
  - Conky Setup: conky.md
  - Gallery: gallery.md
